on:
  push:
#     Sequence of patterns matched against refs/tags
    tags:
    - '*' # Tag events

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v1
      - name: build
        id: build_ipk
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
          mkdir -p /tmp/luci-app-dockerman/usr/lib/lua/luci /tmp/luci-app-dockerman/www/
          [ -d $GITHUB_WORKSPACE/applications/luci-app-dockerman/luasrc ] && cp -R $GITHUB_WORKSPACE/applications/luci-app-dockerman/luasrc/* /tmp/luci-app-dockerman/usr/lib/lua/luci/
          [ -d $GITHUB_WORKSPACE/applications/luci-app-dockerman/root ] && cp -R $GITHUB_WORKSPACE/applications/luci-app-dockerman/root/* /tmp/luci-app-dockerman/
          chmod +x /tmp/luci-app-dockerman/etc/init.d/* >/dev/null 2>&1
          chmod +x /tmp/luci-app-dockerman/etc/uci-defaults/* >/dev/null 2>&1
          [ -d $GITHUB_WORKSPACE/applications/luci-app-dockerman/htdoc ] && cp -R $GITHUB_WORKSPACE/applications/luci-app-dockerman/htdoc/* /tmp/luci-app-dockerman/www/
          [ -d $GITHUB_WORKSPACE/applications/luci-app-dockerman/po ] && sudo -E apt-get -y install gcc make && \
          mkdir -p /tmp/po2lmo && mkdir -p /tmp/luci-app-dockerman/usr/lib/lua/luci/i18n/ && \
          wget -O /tmp/po2lmo/po2lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/po2lmo.c && \
          wget -O /tmp/po2lmo/Makefile https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/Makefile && \
          wget -O /tmp/po2lmo/template_lmo.h https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.h && \
          wget -O /tmp/po2lmo/template_lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.c && \
          cd /tmp/po2lmo && make po2lmo && ./po2lmo $GITHUB_WORKSPACE/applications/luci-app-dockerman/po/zh-cn/dockerman.po /tmp/luci-app-dockerman/usr/lib/lua/luci/i18n/dockerman.zh-cn.lmo
          mkdir -p /tmp/luci-app-dockerman/CONTROL
          cat >/tmp/luci-app-dockerman/CONTROL/control <<EOF
          Package: luci-app-dockerman
          Version: ${TAG}
          Depends: luci-lib-docker, ttyd, docker-ce
          Architecture: all
          Maintainer: lisaac<https://github.com/lisaac/luci-app-dockerman>
          Section: base
          Priority: optional
          Description: Simple Docker manager interface
          Source: http://github.com/lisaac/luci-app-dockerman
          EOF
          cat >/tmp/luci-app-dockerman/CONTROL/postinst <<EOF
          #!/bin/sh
          if [ -z "${IPKG_INSTROOT}" ]; then
          ( . /etc/uci-defaults/luci-app-dockerman ) && rm -f /etc/uci-defaults/luci-app-dockerman
          fi
          exit 0
          EOF
          chmod +x /tmp/luci-app-dockerman/CONTROL/postinst
          wget -O /tmp/ipkg-build https://raw.githubusercontent.com/openwrt/openwrt/openwrt-18.06/scripts/ipkg-build && \
          chmod +x /tmp/ipkg-build && \
          /tmp/ipkg-build -o root -g root /tmp/luci-app-dockerman /tmp
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: /tmp/luci-app-dockerman_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_name: luci-app-dockerman_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_content_type: application/octet-stream
